### ISSUE TITLE
SCg: Не отображать содержимое узла(sc.g-рамки) при его установке

### ISSUE THREAD

**Issue by Ivan-Zhukau** [Ivan-Zhukau/sc-web#10]
**Шаги воспроизведения в scg режиме:**
1. Создать узел
2. Выбрать режим установки содержимого
3. Написать например строку "Qwerty"
4. Нажать "Apply"
**Текущее поведение:**
Ничего не происходит. Окно установки содержимого остается открытым
**Ожидаемое поведение:**
Окно установки содержимого закрывается. В узле отображается установленное содержимое.

**Comment by blrB** [comment]
**Уточнение задания:**
1. Установка содержимого возможно только для ссылок. 
2. Установка содержимого не возможно для узлов и дуг.
3. Отображать установленное содержимое в ссылке.
