### ISSUE TITLE
Выводить ошибку при невозможности подключиться к WebSocket

### ISSUE THREAD

**Issue by rusetski-k** [Ivan-Zhukau/sc-web#104]
Если во время загрузки страницы по какой-то причине блокируется или прерывается соединение с WebSocket-ом sctp-сервера, пользователь продолжает видеть значок процесса загрузки в течение неопределенного времени, что создает у него ложное впечатление о медленной загрузке системы.

**Comment by blrB** [comment]
добавлены alert на ошибку сокета и неправильное закрытие
420e114b34fd2bf8fc78243178ca9b74e45f3a3b
