### ISSUE TITLE
SC-Web Добавить логирование в файл работы sc-web

### ISSUE THREAD

**Issue by Ivan-Zhukau** [Ivan-Zhukau/sc-web#105]
1) подключить библиотеку логирования 
2) добавить точки логирования во всех клиент серверных оперциях.

**Comment by ShunkevichDV** [comment]
Господа, вы в таком случае зависимость добавьте через pip install, оно валится теперь

**Comment by blrB** [comment]
close 6e7f8aa6e5015e6bf388fa4382640ee29705fec2
