### ISSUE TITLE
Некорректное поведение при нажатии Enter в строке поиска по идентификатору

### ISSUE THREAD

**Issue by ShunkevichDV** [Ivan-Zhukau/sc-web#111]
Если курсор мыши не указывает ни на один пункт выпадающего списка, то система не воспринимает нажатие на Enter как подтверждение и не очищает поле ввода.

Ожидаемое поведение:
Нажатие на Enter в любой момент (даже если идентификатор не введен полностью) должно быть эквивалентным клику по верхней позиции в списке предлагаемых идентификаторов. После этого поле для ввода должно возращаться в исходное состояние

**Comment by BobriK502** [comment]
уже сделано))как залить?)

**Comment by blrB** [comment]
Делай pull request, когда разберешься со всеми проблемами, предварительно очистив свой репозиторий от scn редактора
