### ISSUE TITLE
EEKB отображение меню для расширенного просмотра БЗ

### ISSUE THREAD

**Issue by Paulbel** [Ivan-Zhukau/sc-web#139]
При открытии панели с командами расширенного просмотра БЗ ожидается поведение:
![image](https://user-images.githubusercontent.com/15706774/66851415-6245b300-ef83-11e9-8b57-b8c88dcd349a.png)
получаем:
![image](https://user-images.githubusercontent.com/15706774/66851902-7b029880-ef84-11e9-93ee-7c94a0020fad.png)
вероятнее всего ошибка здесь: https://github.com/Ivan-Zhukau/sc-web/blob/22aa610377847e5c4e5b996eb8f8c4098820e4cf/client/css/core.css#L16

**Comment by blrB** [comment]
https://github.com/Ivan-Zhukau/sc-web/commit/9ba0b741654e40fe67e082a9a735f2df017f758e

мой последний коммит уменьшал высоту объекта, так как под ним ничего не было кликабельным, так как я его обрезал до 100px (не знал, что в нем что-то расширяется), в него перестали помещаться другие объекты

**Comment by DBrutski** [comment]
Зависит от того, насколько быстро нужен фикс. 
На данный момент проблема в том, что панель содержащая eekb и строку поиска позицианируется используя [position](http://htmlbook.ru/css/position) relative/fixed. Из-за этого она будет накладываться на элементы под ним.

Возможно будет разумнее эту панель перевести в стандандартный поток блоков

**Comment by Paulbel** [comment]
> [overflow-x](http://htmlbook.ru/css/overflow-x) управляет горизонтальным скролом.
> На картинке же видно, что проблемы с высотой блока.
> Почему ошибка должна быть здесь?

да, ошибка, как мне казалось, была на следующей строке, т.е. overflow-y был задан неправильно, но видимо проблема из- за высоты блока в 100px.

> панель содержащая eekb и строку поиска позицианируется используя [position](http://htmlbook.ru/css/position) relative/fixed

данная панель имеет position: absolute

**Comment by DBrutski** [comment]
Я вижу два решения:
1. Оставить структуру страницы как есть, но поиграть с высотой панели. Сделать, чтобы она занимала только необходимую высоту.
2. Сделать правую панель блоком (убрать position: absolute) и сделать, чтобы на экране панель **не** наезжала на центральный блок

Я за второй вариант т.к.
1. Он упростит структуру страницы (Сделает ее иерархически вложенной)
2. Откроет путь для улучшения UX (например полностью прячущаяся панель)

**Comment by DBrutski** [comment]
@Paulbel так как срочно нужен фикс? Какой вариант выбирать?

Завтра реализую 2-ой, если не против.

**Comment by Paulbel** [comment]
@DBrutski Фикс нужен срочно. Лучше видимо 2-ой вариант, если это ничего не сломает.

**Comment by DBrutski** [comment]
@Paulbel срочно, достаточно растяжимое понятие. Завтра вечером укладывает в срочно?

**Comment by Paulbel** [comment]
@DBrutski более чем.

**Comment by DBrutski** [comment]
Вот как это выглядит:
![image](https://user-images.githubusercontent.com/12894128/66932851-ea3dc280-f040-11e9-9ddf-30cf163e83f5.png)
![image](https://user-images.githubusercontent.com/12894128/66932953-09d4eb00-f041-11e9-9e48-73d3f4b3dc77.png)
Есть замечания или предложения?

**Comment by Paulbel** [comment]
замечаний нет
