### ISSUE TITLE
SCn: Отображение семантической окрестности часто используемых понятий

### ISSUE THREAD

**Issue by DziubinaElena** [Ivan-Zhukau/sc-web#42]
При запросе семантической окрестности наиболее часто используемых понятий таких, как системный идентификатор, основной идентификатор, ключевой sc-элемент и т.д., выдаётся ошибка о том, что страница не отвечает. Последующая работа с системой невозможна.
![problem](https://cloud.githubusercontent.com/assets/11573501/14556536/4c62dd78-0301-11e6-9196-290ab217dc39.png)

**Comment by Ivan-Zhukau** [comment]
Задача была разбита на позадачи, которые должны быть выполнены в следующей очередности:
1) https://github.com/Ivan-Zhukau/sc-web/issues/51
2) https://github.com/Ivan-Zhukau/sc-web/issues/54
3) https://github.com/Ivan-Zhukau/sc-web/issues/53
4) https://github.com/Ivan-Zhukau/sc-web/issues/52
5) https://github.com/Ivan-Zhukau/sc-web/issues/55
