### ISSUE TITLE
SCg: Добавить возможность очистки рабочей области от элементов

### ISSUE THREAD

**Issue by Ivan-Zhukau** [Ivan-Zhukau/sc-web#84]
Кнопка аналог кнопок 'new' в текстовых редакторах

**Comment by blrB** [comment]
это должен быть аналог кнопки new(MDI) или кнопка которая выполняет _ctrl+a_ и _del_?

**Comment by Ivan-Zhukau** [comment]
предыдущий контент должен удалиться и лист должен быть готов к созданию новых конструкций. запоминать, что было до этого не нужно.
