### ISSUE TITLE
Ядро: Некорректный порядок модулей js - сейчас не актуальна, решение есть в dev ветке

### ISSUE THREAD

**Issue by ShunkevichDV** [Ivan-Zhukau/sc-web#92]
Питоновский скрипт, который собирает все jsки в один файл, иногда в зависимости от каких-то условий (точно не знаем, воспроизвести тяжело) кладет модули так, что модуль SCWeb используется раньше, чем объявлен
Это приводит к тому, что в консоли браузера сыпется ошибка SCWeb not defined, после чего не работает ничего дальше
Если в системе возникает такая ошибка, то помочь ничем мы не можем вообще, кроме как посоветовать поменять ноутбук, переустановка локали или даже ОС не помогает
Нужно изменить скрипт таким образом, чтобы порядок модулей был одинаков вне зависимости от того, в каком порядке файловая система отдает файлы

**Comment by Ivan-Zhukau** [comment]
Даниил, фикс для данной задачи есть в ветке dev. там реализована сборка скриптов в sc-web при помощи grunt.
вот пример конфиг файла. https://github.com/Ivan-Zhukau/sc-web/blob/dev/Gruntfile.js
я до конца не проверял этот конкретный комит, поэтому пока не мержил dev и мастер.
но скоро это сделаю

**Comment by Ivan-Zhukau** [comment]
Вроде как перенесли изменения из dev в master. Закрываю задачу
